### ISSUE TITLE
Refactor runtime testsuite

### ISSUE THREAD

**Issue by KvanTTT** [antlr/antlr4#3367]
There is a lot of duplicated code in runtime test classes that can be extracted to a common abstract class. This issue can be assigned this issue to me.

**Comment by ericvergnaud** [comment]
I wouldn't be too worried about this. 
I actually did the work some time ago and then dropped it, because I suspect it could on the long run create problems. Each target has specific requirements, and having the flexibility of changing the tests behavior for a specific target without having to think about other targets is highly valuable, especially given the specific skills of target authors.

**Comment by KvanTTT** [comment]
I don't completely agree. Most part of logic is common, specific parts can be extracted to specific classes. Also, it seems like some logic is excess.

> I suspect it could on the long run create problems

If all tests are green after refactoring then there are no problems. Why type of problems do you mean?

> Each target has specific requirements, and having the flexibility of changing the tests behavior for a specific target without having to think about other targets is highly valuable, especially given the specific skills of target authors.

As I've already said, specific logic can be successfully extracted to concrete classes, it's not a problem. Flexibility remains at the same level. I think we (maintainers and active contributors) shouldn't rely on target authors because they may suddenly leave the project. Moreover, they also may not know about all details (for instance, about [optimizations in my latest PR](https://github.com/antlr/antlr4/pull/3365)).

Also, I would say the new structure of the tests suite will make it easier to add new targets and reduce the number of errors due to duplication.

**Comment by parrt** [comment]
per discussion https://github.com/antlr/antlr4/discussions/3369 easiest/least intrusive change is to use text blocks and convert comments with values into actual strings; tweaking the test classes (descriptors).

**Comment by KvanTTT** [comment]
It's about code itself, not about test data. It will allow us to add tests for new targets more easily and make code more clear.

**Comment by parrt** [comment]
Resolved with https://github.com/antlr/antlr4/pull/3407

**Comment by KvanTTT** [comment]
Actually not resolved. The issue is about something else, about code base, not about test data. Also, merge request is about data transformation, not refactoring.

**Comment by parrt** [comment]
Ah I see. Well, I'm going to close as the test rig works and there's little advantage to refactoring at this point. If we dramatically expand that area then it would be time to Refactor I would say.

**Comment by KvanTTT** [comment]
> If we dramatically expand that area then it would be time to Refactor I would say.

It will allow adding new targets (Rust, maybe Kotlin) much easier. And will simplify code support.

**Comment by parrt** [comment]
Yes, that is true that adding new targets would be easier, but one of my rules for software development is to program for today and not tomorrow ;)  we may never add a new target for example.

**Comment by parrt** [comment]
Change today is not less expensive than a change later when it's actually needed
