### ISSUE TITLE
[Cpp Runtime] MSVC: ANTLRFileStream uses removed "s2ws"

### ISSUE THREAD

**Issue by enricop** [antlr/antlr4#3467]
Hello,

master branch of runtime cpp fails to compile with MSVC on the following line:

![image](https://user-images.githubusercontent.com/667557/148354336-9a5bbedc-6bf0-4e07-9144-a9e49d708c1b.png)

thanks for your support,

**Comment by jcking** [comment]
I believe this should be resolved in 4.10.

**Comment by enricop** [comment]
Hello, thank you for the reply. Looking forward for the release.

**Comment by amykyta3** [comment]
@jcking Release 4.10 still fails to compile. Runtime source does not provide any definition for `antlrcpp::s2ws`:

```
antlr4-cpp-runtime\ANTLRFileStream.cpp(17): error C2653: 'antlrcpp': is not a class or namespace name
antlr4-cpp-runtime\ANTLRFileStream.cpp(17): error C3861: 's2ws': identifier not found
```
From my attempt to upgrade to 4.10: https://github.com/SystemRDL/systemrdl-compiler/runs/6001839774
