### ISSUE TITLE
antlr-4.5.1-complete.jar MANIFEST.MF is missing Main-Class

### ISSUE THREAD

**Issue by makigumo** [antlr/antlr4#961]
There is no Main-Class declaration in the manifest file, so basically running ```java -jar antlr-4.5.1-complete.jar``` is broken resulting in a ```no main manifest attribute, in antlr-4.5.1-complete.jar``` error message.

Release 4.5 did contain the Main-Class declaration.

**Comment by sharwell** [comment]
This is not a duplicate, but it was previously reported as a comment in #956.

**Comment by jiamo** [comment]
Stil have this problem download from http://www.antlr.org/download/antlr-4.5.1-complete.jar

**Comment by dbohdan** [comment]
Same here with Java 1.8.0 on Fedora 22.

**Comment by Filipergv** [comment]
Thanks dbohdan!

**Comment by parrt** [comment]
I just pushed 4.5.1-1 via mvn. Will copy over to website but on top of old 4.5.1.jar as it just adds manifest.

**Comment by krishnak0209** [comment]
I am still getting the error when I use 4.5.1 : Caused by: org.antlr.v4.runtime.RuntimeMetaData$VersionMismatchException: ANTLR Tool version 4.5.1 used for code generation does not match the current runtime version 4.4

**Comment by parrt** [comment]
You must be using 4.4 runtime in classpath but generating code with 4.5.1. a completely different issue than this one.

**Comment by krishnak0209** [comment]
I added 4.4 runtime to my class path, still I am getting this error...org.antlr.v4.runtime.RuntimeMetaData$VersionMismatchException: ANTLR Tool version 4.5.1 used for code generation does not match the current runtime version 4.4...Please help

**Comment by krishnak0209** [comment]
** I added 4.5.1 runtime to my class path

**Comment by parrt** [comment]
well, the message says it all. check your class path
